# mysql-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
data:
  # Thay thế bằng chuỗi đã được mã hóa Base64
  root-password: cm9vdA==
  username: cm9vdA==
  password: cm9vdA==